apiVersion: v2
name: aidelnicek
description: Webová aplikace pro domácnost - zdravé stravování a jídelníčky
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - aidelnicek
  - meals
  - php
maintainers:
  - name: Aidelnicek
